### ISSUE TITLE
Realm まわりで気になっているところ

### ISSUE THREAD

**Issue by funnything** [pichico/MapTodo#27]
(p-r ベースでレビューしていると、設計とかのレビューをおざなりにしてしまうので振り返り)

- MapTodoRealm.sharedRealm.realm は微妙では
    - 最初に sharedRealm に触った thread と、別の thread から触ろうとしたら死ぬ
- `realm.write { ... }` でイケるところを `beginWrite ... commitWrite` と書いているパターン
- モデル内で write トランザクションを制御してしまっている問題
    - トランザクションごとにデータファイルへの flush が発生するのでコストかかりそう
    - write トランザクションを使っている method A から、うっかり別の write トランザクションを使っている method B を呼ぶと死ぬ
    - 決めの問題ではある

**Comment by funnything** [comment]
随想です

**Comment by pichico** [comment]
うおお。ありがとうございます！確認しますー！
